#!/usr/bin/env python3
"""
check_replay_overlap.py
-----------------------
Inspect and quantify the overlap of selected replay items between:
  1) Exp5a-Global (--method=exp5a_global)
  2) FedCBDR     (--method=fedcbdr --gdr_protocol repo_local --tts_mode repo_dual)

WITHOUT MODIFYING ANY EXISTING REPOSITORY CODE.

Modes of operation:
-------------------
1. Parse Mode (Post-run / Offline):
   Compares the automatically generated Exp5 JSONL diagnostic log with the FedCBDR
   stdout log (or redirected log file).
   Usage:
     python check_replay_overlap.py --mode parse \
       --fedcbdr_log fedcbdr.log \
       --exp5_jsonl exp5_greedy_diag_1.0_exp5a_global_exp5a_global_seed2023.jsonl

2. In-Memory Runner Mode:
   Runs both experiments in sequence, dynamically intercepting selection via
   temporary runtime monkey-patching (without modifying files on disk), saving the
   exact selected candidate indices to JSON, and reporting the overlap.
   Usage:
     python check_replay_overlap.py --mode run \
       --dataset cifar10 --tasks 3 --num_users 5 --beta 1.0 --seed 2023 --gpu 0
"""

import argparse
import ast
import glob
import json
import math
import os
import re
import sys
from collections import Counter, defaultdict


# -----------------------------------------------------------------------------
# Parser functions for existing run outputs
# -----------------------------------------------------------------------------

def parse_exp5_jsonl(jsonl_path):
    """
    Parse the JSONL diagnostic file generated by Exp5a.
    Returns:
      selected: dict of {task_id: {client_id: list of local_candidate_ids}}
      details: dict of {task_id: {client_id: {local_candidate_id: dict of info}}}
    """
    if not os.path.exists(jsonl_path):
        raise FileNotFoundError(f"Exp5 JSONL file not found at: {jsonl_path}")

    selected = defaultdict(lambda: defaultdict(list))
    details = defaultdict(lambda: defaultdict(dict))

    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue

            if rec.get("type") == "step":
                task = int(rec["task"])
                client = int(rec["client"])
                local_cand = int(rec["local_candidate"])
                selected[task][client].append(local_cand)
                details[task][client][local_cand] = {
                    "global_candidate": rec.get("global_candidate"),
                    "label": rec.get("label"),
                    "step": rec.get("step"),
                    "phase": rec.get("phase"),
                }

    return selected, details


def parse_fedcbdr_log(log_path):
    """
    Parse FedCBDR stdout log to extract GDR multiplicities.
    Line format from methods/fedcbdr.py line 1181:
      Task <T> GDR draws=<D> unique=<U> p_sum=<P> multiplicities={<dict>} sampling_matrix_norm=<N>

    Returns:
      selected: dict of {task_id: {client_id: list of unique local_candidate_ids}}
      multiplicities: dict of {task_id: {client_id: {local_candidate_id: draw_count}}}
    """
    if not os.path.exists(log_path):
        raise FileNotFoundError(f"FedCBDR log file not found at: {log_path}")

    with open(log_path, "r", encoding="utf-8", errors="replace") as f:
        content = f.read()

    pattern = re.compile(
        r"Task\s+(\d+)\s+GDR\s+draws=\d+\s+unique=\d+.*?multiplicities=(\{.*?\})\s+sampling_matrix_norm",
        re.DOTALL
    )

    selected = defaultdict(lambda: defaultdict(list))
    multiplicities = defaultdict(lambda: defaultdict(dict))

    matches = pattern.findall(content)
    for task_str, mult_str in matches:
        task = int(task_str)
        try:
            mult_dict = ast.literal_eval(mult_str)
        except Exception as e:
            print(f"[Warning] Failed to parse multiplicities for task {task}: {e}")
            continue

        for (client_id, local_id), count in mult_dict.items():
            client_id = int(client_id)
            local_id = int(local_id)
            selected[task][client_id].append(local_id)
            multiplicities[task][client_id][local_id] = int(count)

    return selected, multiplicities


# -----------------------------------------------------------------------------
# Overlap Analysis Core
# -----------------------------------------------------------------------------

def analyze_overlap(exp5_selected, fedcbdr_selected, fedcbdr_mult=None, client_pool_sizes=None):
    """
    Compute overlap metrics between Exp5 and FedCBDR selections.

    Parameters:
      exp5_selected: {task: {client: [local_ids]}}
      fedcbdr_selected: {task: {client: [local_ids]}}
      fedcbdr_mult: {task: {client: {local_id: count}}} (optional)
      client_pool_sizes: {task: {client: pool_size}} (optional, for random chance baseline)
    """
    tasks = sorted(set(exp5_selected.keys()) | set(fedcbdr_selected.keys()))
    if not tasks:
        print("[!] No overlapping tasks found between the two sets of records.")
        return

    print("=" * 88)
    print(" REPLAY ITEM OVERLAP ANALYSIS: Exp5a-Global vs FedCBDR (repo_local)")
    print("=" * 88)

    grand_exp5_total = 0
    grand_fedcbdr_unique = 0
    grand_overlap = 0
    grand_fedcbdr_draws = 0
    grand_draws_on_exp5 = 0

    for task in tasks:
        e_clients = exp5_selected.get(task, {})
        f_clients = fedcbdr_selected.get(task, {})
        clients = sorted(set(e_clients.keys()) | set(f_clients.keys()))

        print(f"\n--- Task {task} ---")
        header = f"{'Client':<8} | {'Exp5a':<7} | {'FedCBDR':<8} | {'Overlap':<7} | {'Jaccard':<8} | {'% of Exp5':<10} | {'% of Fed':<10}"
        if fedcbdr_mult:
            header += f" | {'Draws on Exp5':<14}"
        if client_pool_sizes and task in client_pool_sizes:
            header += f" | {'Random Exp.':<11}"
        print(header)
        print("-" * len(header))

        task_exp5_unique = set()
        task_fedcbdr_unique = set()
        task_overlap_unique = set()
        task_draws = 0
        task_draws_on_exp5 = 0

        for k in clients:
            e_set = set(e_clients.get(k, []))
            f_set = set(f_clients.get(k, []))
            intersect = e_set & f_set
            union = e_set | f_set

            jaccard = (len(intersect) / len(union) * 100.0) if union else 0.0
            pct_exp5 = (len(intersect) / len(e_set) * 100.0) if e_set else 0.0
            pct_fed = (len(intersect) / len(f_set) * 100.0) if f_set else 0.0

            row = f"Client {k:<1} | {len(e_set):<7} | {len(f_set):<8} | {len(intersect):<7} | {jaccard:>6.2f}% | {pct_exp5:>8.2f}% | {pct_fed:>8.2f}%"

            if fedcbdr_mult and task in fedcbdr_mult and k in fedcbdr_mult[task]:
                mult_k = fedcbdr_mult[task][k]
                k_draws = sum(mult_k.values())
                k_hits = sum(mult_k[j] for j in intersect if j in mult_k)
                draw_hit_pct = (k_hits / k_draws * 100.0) if k_draws else 0.0
                row += f" | {k_hits}/{k_draws} ({draw_hit_pct:>5.1f}%)"
                task_draws += k_draws
                task_draws_on_exp5 += k_hits

            if client_pool_sizes and task in client_pool_sizes and k in client_pool_sizes[task]:
                nk = client_pool_sizes[task][k]
                exp_rand = (len(e_set) * len(f_set)) / nk if nk else 0.0
                row += f" | {exp_rand:>6.2f} (N={nk})"

            print(row)

            for j in e_set:
                task_exp5_unique.add((k, j))
            for j in f_set:
                task_fedcbdr_unique.add((k, j))
            for j in intersect:
                task_overlap_unique.add((k, j))

        t_union = task_exp5_unique | task_fedcbdr_unique
        t_jaccard = (len(task_overlap_unique) / len(t_union) * 100.0) if t_union else 0.0
        t_pct_exp5 = (len(task_overlap_unique) / len(task_exp5_unique) * 100.0) if task_exp5_unique else 0.0
        t_pct_fed = (len(task_overlap_unique) / len(task_fedcbdr_unique) * 100.0) if task_fedcbdr_unique else 0.0

        print("-" * len(header))
        t_summary = f"{'Total':<8} | {len(task_exp5_unique):<7} | {len(task_fedcbdr_unique):<8} | {len(task_overlap_unique):<7} | {t_jaccard:>6.2f}% | {t_pct_exp5:>8.2f}% | {t_pct_fed:>8.2f}%"
        if fedcbdr_mult and task_draws > 0:
            t_draw_pct = (task_draws_on_exp5 / task_draws * 100.0)
            t_summary += f" | {task_draws_on_exp5}/{task_draws} ({t_draw_pct:>5.1f}%)"
        print(t_summary)

        grand_exp5_total += len(task_exp5_unique)
        grand_fedcbdr_unique += len(task_fedcbdr_unique)
        grand_overlap += len(task_overlap_unique)
        grand_fedcbdr_draws += task_draws
        grand_draws_on_exp5 += task_draws_on_exp5

    # Overall Summary
    print("\n" + "=" * 88)
    print(" OVERALL MULTI-TASK SUMMARY")
    print("=" * 88)
    grand_union = grand_exp5_total + grand_fedcbdr_unique - grand_overlap
    g_jaccard = (grand_overlap / grand_union * 100.0) if grand_union else 0.0
    g_pct_exp5 = (grand_overlap / grand_exp5_total * 100.0) if grand_exp5_total else 0.0
    g_pct_fed = (grand_overlap / grand_fedcbdr_unique * 100.0) if grand_fedcbdr_unique else 0.0

    print(f"Total Unique Replay Items Selected by Exp5a-Global : {grand_exp5_total}")
    print(f"Total Unique Replay Items Selected by FedCBDR       : {grand_fedcbdr_unique}")
    print(f"Identical Items Selected by BOTH Methods           : {grand_overlap}")
    print(f"Overall Jaccard Similarity                         : {g_jaccard:.2f}%")
    print(f"Overlap % of Exp5a-Global Pool                     : {g_pct_exp5:.2f}%")
    print(f"Overlap % of FedCBDR Pool                          : {g_pct_fed:.2f}%")
    if grand_fedcbdr_draws > 0:
        g_draw_pct = (grand_draws_on_exp5 / grand_fedcbdr_draws * 100.0)
        print(f"FedCBDR Draws Landing on Exp5a Candidates         : {grand_draws_on_exp5}/{grand_fedcbdr_draws} ({g_draw_pct:.2f}%)")
    print("=" * 88)


# -----------------------------------------------------------------------------
# In-Memory Runner (Dynamic Interception without File Modification)
# -----------------------------------------------------------------------------

def run_and_capture():
    """
    Run Exp5a-Global and FedCBDR sequentially in Python, dynamically intercepting
    selected indices in-memory without changing any repository files.
    """
    import torch
    from main import args_parser, get_learner
    from utils.data_manager import DataManager, setup_seed, partition_data

    # Common parameters for both runs
    common_args = {
        "group": "c100t5",
        "dataset": "cifar10",
        "tasks": 3,
        "num_users": 5,
        "beta": 1.0,
        "seed": 2023,
        "local_bs": 128,
        "local_ep": 2,
        "com_round": 100,
        "wandb": 0,
        "class_shuffle": 1,
        "net": "resnet18",
        "frac": 1.0,
        "num_worker": 4,
        "mulc": "fork" if sys.platform != "win32" else "spawn",
        "weight_decay": 1e-5,
        "syn_bs": 1,
        "local_lr": 4e-2,
        "r": 0.015,
        "ltc": 5,
        "pre": 0.4,
        "cur": 0.2,
        "type": -1,
        "syn": 1,
        "spec": "t1",
        "repeat_rate": 1,
        "exp5a_rank": 128,
        "exp5a_svd_oversampling": 16,
        "exp5a_mask_layers": 12,
        "exp5a_mask_seed_offset": 5000,
        "exp5a_target_mode": "budget_scaled_sum",
        "exp5a_tau": 0.05,
        "exp6_max_passes": 5,
        "exp6_improvement_tol": 1e-8,
        "exp6b_lambda": 1.0,
        "exp6b_max_passes": 5,
        "exp6b_improvement_tol": 1e-8,
        "tau_old": 0.9,
        "tau_new": 1.1,
        "w_old": 1.1,
        "w_new": 0.9,
        "scale": False,
        "mem_size": 50,
        "fedcbdr_legacy_mem_size": False,
        "gdr_protocol": "repo_local",
        "gdr_mask_mode": "dense_qr",
        "gdr_leverage_mode": "economy",
        "gdr_rank": None,
        "gdr_normalization_mode": "global",
        "gdr_replacement": "with",
        "gdr_correction_mode": "none",
        "tts_mode": "repo_dual",
        "joint_loss": "tts",
        "fedcbdr_lr_schedule": "constant",
        "repo_dual": False,
        "exp5_distill_loss": False,
        "exp5_single_distill_loss": False,
        "gpu": 0,
    }

    # Set CIFAR-10 classes and budget
    common_args["num_class"] = 10
    budget = {"cifar10": {3: 450, 5: 300}}
    common_args["gdr_task_budget"] = budget["cifar10"][3]
    common_args["init_cls"] = int(common_args["num_class"] / common_args["tasks"])
    common_args["increment"] = common_args["init_cls"]

    captured_exp5 = defaultdict(lambda: defaultdict(list))
    captured_fedcbdr = defaultdict(lambda: defaultdict(list))
    captured_fedcbdr_mult = defaultdict(lambda: defaultdict(dict))

    # --- 1. RUN EXP5A-GLOBAL ---
    print("\n" + "=" * 80)
    print(" [1/2] RUNNING EXP5A-GLOBAL")
    print("=" * 80)
    import methods.exp5 as exp5_module
    orig_exp5_commit = exp5_module.Exp5Base._commit_replay_memory

    def hooked_exp5_commit(self, selected_by_client, user_groups, train_dataset):
        task = self._cur_task
        for k in range(self.num_users):
            local_ids = sorted(selected_by_client[k])
            captured_exp5[task][k] = [int(i) for i in local_ids]
        return orig_exp5_commit(self, selected_by_client, user_groups, train_dataset)

    exp5_module.Exp5Base._commit_replay_memory = hooked_exp5_commit

    args_exp5 = dict(common_args)
    args_exp5["method"] = "exp5a_global"
    args_exp5["exp_name"] = "exp5a_global"

    setup_seed(args_exp5["seed"])
    dm_exp5 = DataManager(
        args_exp5["dataset"],
        args_exp5["class_shuffle"],
        args_exp5["seed"],
        args_exp5["init_cls"],
        args_exp5["increment"],
        args_exp5,
    )
    args_exp5["class_order"] = dm_exp5.get_class_order()
    learner_exp5 = get_learner(args_exp5["method"], args_exp5)

    for task in range(dm_exp5.nb_tasks):
        learner_exp5.incremental_train(dm_exp5)
        learner_exp5.after_task()

    # Restore original method
    exp5_module.Exp5Base._commit_replay_memory = orig_exp5_commit

    # Save Exp5 selections to JSON
    with open("captured_exp5a_global_replay.json", "w") as f:
        json.dump(captured_exp5, f, indent=2)
    print("[+] Exp5a-Global replay selections saved to captured_exp5a_global_replay.json")

    # --- 2. RUN FEDCBDR ---
    print("\n" + "=" * 80)
    print(" [2/2] RUNNING FEDCBDR")
    print("=" * 80)
    import methods.fedcbdr as fedcbdr_module
    orig_fedcbdr_select = fedcbdr_module.RepoStyleReplaySelector.select

    def hooked_fedcbdr_select(self, local_features):
        selection = orig_fedcbdr_select(self, local_features)
        # Task is retrieved from learner context
        task = getattr(current_fedcbdr_learner, "_cur_task", 0)
        for client_id, values in selection.items():
            ids = [int(v.local_index) for v in values]
            counts = Counter(ids)
            captured_fedcbdr[task][client_id] = sorted(list(counts.keys()))
            captured_fedcbdr_mult[task][client_id] = dict(counts)
        return selection

    fedcbdr_module.RepoStyleReplaySelector.select = hooked_fedcbdr_select

    args_fedcbdr = dict(common_args)
    args_fedcbdr["method"] = "fedcbdr"
    args_fedcbdr["exp_name"] = "fedcbdr"

    setup_seed(args_fedcbdr["seed"])
    dm_fedcbdr = DataManager(
        args_fedcbdr["dataset"],
        args_fedcbdr["class_shuffle"],
        args_fedcbdr["seed"],
        args_fedcbdr["init_cls"],
        args_fedcbdr["increment"],
        args_fedcbdr,
    )
    args_fedcbdr["class_order"] = dm_fedcbdr.get_class_order()
    learner_fedcbdr = get_learner(args_fedcbdr["method"], args_fedcbdr)
    current_fedcbdr_learner = learner_fedcbdr

    for task in range(dm_fedcbdr.nb_tasks):
        learner_fedcbdr.incremental_train(dm_fedcbdr)
        learner_fedcbdr.after_task()

    # Restore original method
    fedcbdr_module.RepoStyleReplaySelector.select = orig_fedcbdr_select

    # Save FedCBDR selections to JSON
    with open("captured_fedcbdr_replay.json", "w") as f:
        json.dump(
            {"unique": captured_fedcbdr, "multiplicities": captured_fedcbdr_mult},
            f, indent=2
        )
    print("[+] FedCBDR replay selections saved to captured_fedcbdr_replay.json")

    # --- 3. COMPARE ---
    analyze_overlap(captured_exp5, captured_fedcbdr, captured_fedcbdr_mult)


# -----------------------------------------------------------------------------
# Main CLI entry point
# -----------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Check replay overlap between Exp5a-Global and FedCBDR.")
    parser.add_argument("--mode", type=str, choices=["parse", "run"], default="parse",
                        help="'parse' for existing logs/JSONL, 'run' to execute both methods in sequence")
    parser.add_argument("--exp5_jsonl", type=str, default=None,
                        help="Path to exp5_greedy_diag_*.jsonl file")
    parser.add_argument("--fedcbdr_log", type=str, default=None,
                        help="Path to fedcbdr stdout log file")

    args = parser.parse_args()

    if args.mode == "run":
        run_and_capture()
        return

    # In parse mode:
    # Auto-detect exp5 jsonl if not provided
    exp5_file = args.exp5_jsonl
    if not exp5_file:
        candidates = glob.glob("exp5_greedy_diag_*exp5a_global*seed2023*.jsonl")
        if candidates:
            exp5_file = candidates[0]
            print(f"[Auto-detected Exp5 JSONL] {exp5_file}")
        else:
            candidates_any = glob.glob("exp5_greedy_diag_*.jsonl")
            if candidates_any:
                exp5_file = candidates_any[0]
                print(f"[Auto-detected Exp5 JSONL] {exp5_file}")

    fedcbdr_file = args.fedcbdr_log
    if not fedcbdr_file:
        for fname in ["fedcbdr.log", "fedcbdr_output.txt", "fedcbdr.txt"]:
            if os.path.exists(fname):
                fedcbdr_file = fname
                print(f"[Auto-detected FedCBDR log] {fedcbdr_file}")
                break

    if not exp5_file or not fedcbdr_file:
        print("\n[!] Please specify the input files:")
        print("    --exp5_jsonl  <path_to_exp5_diag.jsonl>")
        print("    --fedcbdr_log <path_to_fedcbdr.log>")
        print("\nExample:")
        print("    python check_replay_overlap.py --mode parse \\\n"
              "      --exp5_jsonl exp5_greedy_diag_1.0_exp5a_global_exp5a_global_seed2023.jsonl \\\n"
              "      --fedcbdr_log fedcbdr.log\n")
        sys.exit(1)

    print(f"Loading Exp5 selections from   : {exp5_file}")
    exp5_selected, exp5_details = parse_exp5_jsonl(exp5_file)

    print(f"Loading FedCBDR selections from: {fedcbdr_file}")
    fedcbdr_selected, fedcbdr_mult = parse_fedcbdr_log(fedcbdr_file)

    analyze_overlap(exp5_selected, fedcbdr_selected, fedcbdr_mult)


if __name__ == "__main__":
    main()
